version: '3.3'

services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: buayakecil
            MYSQL_DATABASE: reservasi
            MYSQL_USER: userawan
            MYSQL_PASSWORD: buayakecil
        volumes:
            - ./reservasi:/docker-entrypoint-initdb.d
            - dbdata:/var/lib/mysql
        networks:
            ip-docker:
                ipv4_address: 10.5.5.5

    worker1:
        image: reservasi-flask-images
        depends_on:
            - db
        restart: always
        environment: 
            DB_HOST: 10.5.5.5
            DB_USERNAME: userawan
            DB_PASSWORD: buayakecil
            DB_NAME: reservasi
        networks:
            ip-docker:
                ipv4_address: 10.5.5.10

    worker2:
        image: reservasi-flask-images
        depends_on:
            - db
        restart: always
        environment: 
            DB_HOST: 10.5.5.5
            DB_USERNAME: userawan
            DB_PASSWORD: buayakecil
            DB_NAME: reservasi
        networks:
            ip-docker:
                ipv4_address: 10.5.5.11

    worker3:
        image: reservasi-flask-images
        depends_on:
            - db
        restart: always
        environment:
            DB_HOST: 10.5.5.5
            DB_USERNAME: userawan
            DB_PASSWORD: buayakecil
            DB_NAME: reservasi
        networks:
            ip-docker:
                ipv4_address: 10.5.5.12

    load-balancer:
        image: nginx:stable-alpine
        depends_on:
            - worker1
            - worker2
            - worker3
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 1998:80
        networks: 
            ip-docker:
                ipv4_address: 10.5.5.6

volumes:
    dbdata:

networks: 
    ip-docker:
        driver: bridge
        ipam: 
            config:
                - subnet: 10.5.5.0/24
